name: Python CI

on:
  push:
    branches:
      - Game
  pull_request:
    branches:
      - Game

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 flake8-html

      - name: Run flake8 (linting)
        run: |
          flake8 . --max-line-length=79 --format=html --output-file=flake8_report.html

      - name: Upload flake8 HTML report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: flake8_report.html

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings --format=html --output=pytest_report.html

      - name: Upload pytest HTML report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest_report.html
